server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    org:
      springframework:
        security: DEBUG

security:
  ignored: /**